import Head from "next/head";
import { StyledMainContent } from "../styled-components/styled-mainview";
import HomeComponent from "../components/homecomponent/homecomponent";
import Sidebar from "../components/Sidebar/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Sidebar />
        <StyledMainContent className="main-content">
          <div className="lines">
            <div className="line-1"></div>
            <div className="line-2"></div>
            <div className="line-3"></div>
            <div className="line-4"></div>
          </div>
          <HomeComponent />
        </StyledMainContent>
      </main>
    </>
  );
}
